(eval-when-compile    (require 'color-theme))
(defun my-color-theme ()
  "Color theme by wanglei, created 2011-11-08."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "#000000000000")
      (background-mode . dark)
      (background-toolbar-color . "#000000000000")
      (border-color . "black")
      (bottom-toolbar-shadow-color . "red")
      (cursor-color . "green")
      (foreground-color . "#00CC00")
      (mouse-color . "black")
      (top-toolbar-shadow-color . "#f5f5f5f5f5f5"))
     ((ac-fuzzy-cursor-color . "red")
      (goto-address-mail-face . message-header-to-face)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . info-xref)
      (goto-address-url-mouse-face . highlight)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (php-default-face . default)
      (tags-tag-face . default)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "black" :foreground "#00CC00" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
     (Buffer-menu-buffer-face ((t (:bold t :weight bold))))
     (ac-candidate-face ((t (:background "lightgray" :foreground "black"))))
     (ac-completion-face ((t (:foreground "darkgray" :underline t))))
     (ac-selection-face ((t (:background "steelblue" :foreground "white"))))
     (bbdb-company ((t (:foreground "pale green"))))
     (bbdb-field-name ((t (:foreground "medium sea green"))))
     (bbdb-field-value ((t (:foreground "dark sea green"))))
     (bbdb-name ((t (:bold t :foreground "pale green" :weight bold))))
     (bg:erc-color-face0 ((t (:background "White"))))
     (bg:erc-color-face1 ((t (:background "black"))))
     (bg:erc-color-face10 ((t (:background "lightblue1"))))
     (bg:erc-color-face11 ((t (:background "cyan"))))
     (bg:erc-color-face12 ((t (:background "blue"))))
     (bg:erc-color-face13 ((t (:background "deeppink"))))
     (bg:erc-color-face14 ((t (:background "gray50"))))
     (bg:erc-color-face15 ((t (:background "gray90"))))
     (bg:erc-color-face2 ((t (:background "blue4"))))
     (bg:erc-color-face3 ((t (:background "green4"))))
     (bg:erc-color-face4 ((t (:background "red"))))
     (bg:erc-color-face5 ((t (:background "brown"))))
     (bg:erc-color-face6 ((t (:background "purple"))))
     (bg:erc-color-face7 ((t (:background "orange"))))
     (bg:erc-color-face8 ((t (:background "yellow"))))
     (bg:erc-color-face9 ((t (:background "green"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant oblique :weight semi-bold))))
     (border ((t (:background "black"))))
     (border-glyph ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffers-tab ((t (:bold t :background "gray75" :foreground "red" :weight bold))))
     (button ((t (:underline t))))
     (calendar-today-face ((t (:foreground "lemon chiffon" :underline t))))
     (change-log-acknowledgement-face ((t (:foreground "LightBlue"))))
     (change-log-conditionals-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (change-log-date-face ((t (:foreground "LightSalmon"))))
     (change-log-email-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (change-log-file-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (change-log-function-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (change-log-list-face ((t (:foreground "Salmon"))))
     (change-log-name-face ((t (:foreground "Aquamarine"))))
     (comint-highlight-input ((t (nil))))
     (comint-highlight-prompt ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (completions-annotations ((t (:italic t :slant oblique :foreground "#00CC00" :background "black"))))
     (completions-common-part ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#00CC00" :background "black" :stipple nil :height 1))))
     (completions-first-difference ((t (:bold t :weight bold :foreground "#00CC00" :background "black"))))
     (cperl-array-face ((t (:bold t :background "lightyellow2" :foreground "Blue" :weight bold))))
     (cperl-hash-face ((t (:italic t :bold t :background "lightyellow2" :foreground "Red" :slant italic :weight bold))))
     (cperl-nonoverridable-face ((t (:foreground "chartreuse3"))))
     (cscope-file-face ((t (:foreground "blue"))))
     (cscope-function-face ((t (:foreground "magenta"))))
     (cscope-line-face ((t (:foreground "green"))))
     (cscope-line-number-face ((t (:foreground "red"))))
     (cscope-mouse-face ((t (:background "blue" :foreground "white"))))
     (cursor ((t (:background "green"))))
     (custom-button-face ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (custom-button-pressed-face ((t (nil))))
     (custom-changed-face ((t (:italic t :background "black" :foreground "#00CC00" :slant oblique))))
     (custom-comment-face ((t (nil))))
     (custom-comment-tag-face ((t (nil))))
     (custom-documentation-face ((t (nil))))
     (custom-face-tag-face ((t (nil))))
     (custom-group-tag-face ((t (nil))))
     (custom-group-tag-face-1 ((t (nil))))
     (custom-invalid-face ((t (:background "black" :foreground "#00CC00" :strike-through t))))
     (custom-modified-face ((t (nil))))
     (custom-rogue-face ((t (nil))))
     (custom-saved-face ((t (nil))))
     (custom-set-face ((t (nil))))
     (custom-state-face ((t (nil))))
     (custom-variable-button-face ((t (nil))))
     (custom-variable-tag-face ((t (nil))))
     (cyan ((t (:foreground "cyan"))))
     (diary-face ((t (:bold t :foreground "red" :weight bold))))
     (diff-added-face ((t (nil))))
     (diff-changed-face ((t (nil))))
     (diff-context-face ((t (:foreground "grey70"))))
     (diff-file-header-face ((t (:bold t :weight bold))))
     (diff-function-face ((t (:foreground "grey70"))))
     (diff-header-face ((t (:foreground "light salmon"))))
     (diff-hunk-header-face ((t (:foreground "light salmon"))))
     (diff-index-face ((t (:bold t :weight bold))))
     (diff-nonexistent-face ((t (:bold t :weight bold))))
     (diff-removed-face ((t (nil))))
     (dired-face-boring ((t (:foreground "Gray65"))))
     (dired-face-directory ((t (:bold t :foreground "sky blue" :weight bold))))
     (dired-face-executable ((t (:foreground "SeaGreen"))))
     (dired-face-flagged ((t (:background "LightSlateGray" :foreground "tomato"))))
     (dired-face-marked ((t (:background "PaleVioletRed" :foreground "light salmon"))))
     (dired-face-permissions ((t (:background "grey75" :foreground "black"))))
     (dired-face-setuid ((t (:foreground "Red"))))
     (dired-face-socket ((t (:foreground "magenta"))))
     (dired-face-symlink ((t (:foreground "cyan"))))
     (display-time-mail-balloon-enhance-face ((t (:background "orange"))))
     (display-time-mail-balloon-gnus-group-face ((t (:foreground "blue"))))
     (display-time-time-balloon-face ((t (:foreground "red"))))
     (ecb-bucket-token-face ((t (:bold t :weight bold))))
     (ecb-default-general-face ((t (nil))))
     (ecb-default-highlight-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-directories-general-face ((t (nil))))
     (ecb-directory-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-history-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-history-general-face ((t (nil))))
     (ecb-method-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-methods-general-face ((t (nil))))
     (ecb-source-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-source-in-directories-buffer-face ((t (:foreground "medium blue"))))
     (ecb-sources-general-face ((t (nil))))
     (ecb-token-header-face ((t (:background "SeaGreen1"))))
     (ecb-type-token-class-face ((t (:bold t :weight bold))))
     (ecb-type-token-enum-face ((t (:bold t :weight bold))))
     (ecb-type-token-group-face ((t (:bold t :foreground "dimgray" :weight bold))))
     (ecb-type-token-interface-face ((t (:bold t :weight bold))))
     (ecb-type-token-struct-face ((t (:bold t :weight bold))))
     (ecb-type-token-typedef-face ((t (:bold t :weight bold))))
     (ediff-current-diff-face-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-face-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-face-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-face-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-face-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-face-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-face-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-face-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-face-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-face-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-face-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-face-Ancestor ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-C ((t (:background "Grey" :foreground "White"))))
     (eieio-custom-slot-tag-face ((t (:foreground "light blue"))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold :foreground "#00CC00" :background "black"))))
     (erc-action-face ((t (:bold t :weight semi-bold))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-current-nick-face ((t (:bold t :foreground "LightSeaGreen" :weight semi-bold))))
     (erc-dangerous-host-face ((t (:foreground "red"))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "IndianRed"))))
     (erc-error-face ((t (:bold t :background "darkblue" :foreground "#00CC00" :weight semi-bold))))
     (erc-fool-face ((t (:foreground "dim gray"))))
     (erc-highlight-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-input-face ((t (:foreground "springgreen"))))
     (erc-inverse-face ((t (:bold t :background "Darkgreen" :foreground "Black" :weight semi-bold))))
     (erc-keyword-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-nick-default-face ((t (:bold t :weight semi-bold))))
     (erc-nick-msg-face ((t (:bold t :foreground "springgreen" :weight semi-bold))))
     (erc-notice-face ((t (:foreground "seagreen" :weight normal))))
     (erc-pal-face ((t (:bold t :foreground "Magenta" :weight bold))))
     (erc-prompt-face ((t (:bold t :background "lightBlue2" :foreground "Black" :weight semi-bold))))
     (erc-timestamp-face ((t (:foreground "seagreen" :weight normal))))
     (erc-underline-face ((t (:underline t))))
     (escape-glyph ((t (:foreground "cyan"))))
     (eshell-ls-archive-face ((t (:bold t :foreground "Orchid" :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "OrangeRed"))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-ls-directory-face ((t (:bold t :foreground "Blue" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (eshell-ls-missing-face ((t (:bold t :foreground "Red" :weight bold))))
     (eshell-ls-picture-face ((t (:foreground "Violet"))))
     (eshell-ls-product-face ((t (:foreground "OrangeRed"))))
     (eshell-ls-readonly-face ((t (:foreground "Brown"))))
     (eshell-ls-special-face ((t (:bold t :foreground "Magenta" :weight bold))))
     (eshell-ls-symlink-face ((t (:bold t :foreground "DarkCyan" :weight bold))))
     (eshell-ls-text-face ((t (:foreground "medium aquamarine"))))
     (eshell-ls-todo-face ((t (:bold t :foreground "aquamarine" :weight bold))))
     (eshell-ls-unreadable-face ((t (:foreground "Grey30"))))
     (eshell-prompt-face ((t (:bold t :foreground "Red" :weight bold))))
     (eshell-test-failed-face ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-test-ok-face ((t (:bold t :foreground "Green" :weight bold))))
     (excerpt ((t (:italic t :slant italic))))
     (fg:erc-color-face0 ((t (:foreground "White"))))
     (fg:erc-color-face1 ((t (:foreground "black"))))
     (fg:erc-color-face10 ((t (:foreground "lightblue1"))))
     (fg:erc-color-face11 ((t (:foreground "cyan"))))
     (fg:erc-color-face12 ((t (:foreground "blue"))))
     (fg:erc-color-face13 ((t (:foreground "deeppink"))))
     (fg:erc-color-face14 ((t (:foreground "gray50"))))
     (fg:erc-color-face15 ((t (:foreground "gray90"))))
     (fg:erc-color-face2 ((t (:foreground "blue4"))))
     (fg:erc-color-face3 ((t (:foreground "green4"))))
     (fg:erc-color-face4 ((t (:foreground "red"))))
     (fg:erc-color-face5 ((t (:foreground "brown"))))
     (fg:erc-color-face6 ((t (:foreground "purple"))))
     (fg:erc-color-face7 ((t (:foreground "orange"))))
     (fg:erc-color-face8 ((t (:foreground "yellow"))))
     (fg:erc-color-face9 ((t (:foreground "green"))))
     (file-name-shadow ((t (:foreground "yellow"))))
     (fixed ((t (:bold t :weight bold))))
     (fixed-pitch ((t (nil))))
     (fl-comment-face ((t (:foreground "pink"))))
     (fl-doc-string-face ((t (:foreground "purple"))))
     (fl-function-name-face ((t (:foreground "red"))))
     (fl-keyword-face ((t (:foreground "cyan"))))
     (fl-string-face ((t (:foreground "green"))))
     (fl-type-face ((t (:foreground "yellow"))))
     (flyspell-duplicate-face ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect-face ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-latex-string-face ((t (:bold t :background "black" :foreground "seagreen" :weight semi-bold))))
     (font-latex-warning-face ((t (:bold t :background "darkblue" :foreground "#00CC00" :weight semi-bold))))
     (font-lock-builtin-face ((t (:foreground "seagreen1"))))
     (font-lock-comment-delimiter-face ((t (:bold t :weight bold :background "black" :foreground "red1"))))
     (font-lock-comment-face ((t (:bold t :background "black" :foreground "medium spring green" :weight bold))))
     (font-lock-constant-face ((t (nil))))
     (font-lock-doc-face ((t (:bold t :background "black" :foreground "seagreen" :weight semi-bold))))
     (font-lock-doc-string-face ((t (:bold t :foreground "red" :weight bold))))
     (font-lock-function-name-face ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (font-lock-keyword-face ((t (:bold t :background "black" :foreground "green" :underline t :weight semi-bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:bold t :foreground "#00ccdd" :weight bold))))
     (font-lock-reference-face ((t (:foreground "red3"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold :foreground "#00CC00" :background "black"))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold :foreground "#00CC00" :background "black"))))
     (font-lock-string-face ((t (:bold t :background "black" :foreground "seagreen" :weight semi-bold))))
     (font-lock-type-face ((t (nil))))
     (font-lock-variable-name-face ((t (nil))))
     (font-lock-warning-face ((t (:bold t :background "darkblue" :foreground "#00CC00" :weight semi-bold))))
     (fringe ((t (:background "#151515" :foreground "#00CC00"))))
     (gdb-arrow-face ((t (:bold t :background "yellow" :foreground "red" :weight bold))))
     (gnus-cite-attribution-face ((t (:italic t :background "black" :foreground "#00CC00" :slant italic))))
     (gnus-cite-face-1 ((t (:background "black" :foreground "springgreen"))))
     (gnus-cite-face-10 ((t (nil))))
     (gnus-cite-face-11 ((t (nil))))
     (gnus-cite-face-2 ((t (:background "black" :foreground "lightseagreen"))))
     (gnus-cite-face-3 ((t (:background "black" :foreground "darkseagreen"))))
     (gnus-cite-face-4 ((t (:background "black" :foreground "forestgreen"))))
     (gnus-cite-face-5 ((t (:background "black" :foreground "springgreen"))))
     (gnus-cite-face-6 ((t (:background "black" :foreground "springgreen"))))
     (gnus-cite-face-7 ((t (:background "black" :foreground "springgreen"))))
     (gnus-cite-face-8 ((t (:background "black" :foreground "springgreen"))))
     (gnus-cite-face-9 ((t (:background "black" :foreground "springgreen"))))
     (gnus-emphasis-bold ((t (:bold t :weight semi-bold))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t :slant italic :weight semi-bold))))
     (gnus-emphasis-highlight-words ((t (:bold t :background "black" :foreground "#00CC00" :underline t :weight bold))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-strikethru ((t (nil))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t :weight semi-bold))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :underline t :slant italic :weight semi-bold))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t :slant italic))))
     (gnus-group-mail-1-empty-face ((t (nil))))
     (gnus-group-mail-1-face ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (gnus-group-mail-2-empty-face ((t (nil))))
     (gnus-group-mail-2-face ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (gnus-group-mail-3-empty-face ((t (nil))))
     (gnus-group-mail-3-face ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (gnus-group-mail-low-empty-face ((t (nil))))
     (gnus-group-mail-low-face ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (gnus-group-news-1-empty-face ((t (nil))))
     (gnus-group-news-1-face ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (gnus-group-news-2-empty-face ((t (nil))))
     (gnus-group-news-2-face ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (gnus-group-news-3-empty-face ((t (nil))))
     (gnus-group-news-3-face ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (gnus-group-news-4-empty-face ((t (nil))))
     (gnus-group-news-4-face ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (gnus-group-news-5-empty-face ((t (nil))))
     (gnus-group-news-5-face ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (gnus-group-news-6-empty-face ((t (nil))))
     (gnus-group-news-6-face ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (gnus-group-news-low-empty-face ((t (nil))))
     (gnus-group-news-low-face ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (gnus-header-content-face ((t (:italic t :background "black" :foreground "springgreen" :slant italic))))
     (gnus-header-from-face ((t (nil))))
     (gnus-header-name-face ((t (nil))))
     (gnus-header-newsgroups-face ((t (nil))))
     (gnus-header-subject-face ((t (nil))))
     (gnus-picons-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-server-agent-face ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (gnus-server-closed-face ((t (:italic t :foreground "Light Steel Blue" :slant italic))))
     (gnus-server-denied-face ((t (:bold t :foreground "Pink" :weight semi-bold))))
     (gnus-server-offline-face ((t (:bold t :foreground "Yellow" :weight bold))))
     (gnus-server-opened-face ((t (:bold t :foreground "Green1" :weight semi-bold))))
     (gnus-signature-face ((t (:background "black" :foreground "springgreen" :slant normal))))
     (gnus-splash-face ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (gnus-summary-cancelled-face ((t (:background "black" :foreground "#00CC00" :strike-through t))))
     (gnus-summary-high-ancient-face ((t (nil))))
     (gnus-summary-high-read-face ((t (nil))))
     (gnus-summary-high-ticked-face ((t (:bold t :background "black" :foreground "seagreen" :weight bold))))
     (gnus-summary-high-undownloaded-face ((t (:bold t :foreground "LightGray" :weight bold))))
     (gnus-summary-high-unread-face ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (gnus-summary-low-ancient-face ((t (nil))))
     (gnus-summary-low-read-face ((t (nil))))
     (gnus-summary-low-ticked-face ((t (nil))))
     (gnus-summary-low-undownloaded-face ((t (:italic t :foreground "LightGray" :slant italic :weight normal))))
     (gnus-summary-low-unread-face ((t (:italic t :bold t :background "black" :foreground "#00CC00" :slant italic :weight bold))))
     (gnus-summary-normal-ancient-face ((t (nil))))
     (gnus-summary-normal-read-face ((t (nil))))
     (gnus-summary-normal-ticked-face ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (gnus-summary-normal-undownloaded-face ((t (:foreground "LightGray" :weight normal))))
     (gnus-summary-normal-unread-face ((t (nil))))
     (gnus-summary-selected-face ((t (:background "#101010" :underline t))))
     (gnus-x-face ((t (:background "white" :foreground "black"))))
     (green ((t (:foreground "green"))))
     (gui-button-face ((t (:background "grey75" :foreground "black"))))
     (gui-element ((t (:background "Gray80" :foreground "black"))))
     (header-line ((t (nil))))
     (help-argument-name ((t (nil))))
     (highlight ((t (:bold t :background "darkgreen" :foreground "#00CC00" :weight bold))))
     (highlight-changes-delete-face ((t (:foreground "red" :underline t))))
     (highlight-changes-face ((t (:foreground "red"))))
     (highline-face ((t (:background "paleturquoise"))))
     (holiday-face ((t (:bold t :background "pink" :foreground "peru" :weight bold))))
     (hyper-apropos-documentation ((t (:foreground "#aaaaaa"))))
     (hyper-apropos-heading ((t (:bold t :foreground "#999999" :weight bold))))
     (hyper-apropos-hyperlink ((t (:bold t :foreground "Violet" :weight bold))))
     (hyper-apropos-major-heading ((t (:bold t :foreground "#ff0000" :weight bold))))
     (hyper-apropos-section-heading ((t (:italic t :bold t :foreground "#33aa55" :slant italic :weight bold))))
     (hyper-apropos-warning ((t (:bold t :foreground "red" :weight bold))))
     (ido-first-match-face ((t (:bold t :weight bold))))
     (ido-indicator-face ((t (:background "red" :foreground "yellow" :width condensed))))
     (ido-only-match-face ((t (:foreground "ForestGreen"))))
     (ido-subdir-face ((t (:foreground "red"))))
     (info-header-xref ((t (:bold t :foreground "DodgerBlue1" :weight bold))))
     (info-menu-5 ((t (:underline t))))
     (info-node ((t (:italic t :bold t :foreground "DodgerBlue1" :underline t :slant italic :weight bold))))
     (info-xref ((t (:bold t :foreground "DodgerBlue1" :weight bold))))
     (isearch ((t (:background "seagreen" :foreground "black"))))
     (isearch-fail ((t (:background "red"))))
     (isearch-secondary ((t (:foreground "red3"))))
     (italic ((t (:italic t :background "black" :foreground "#00CC00" :slant oblique))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-db-active-breakpoint-face ((t (:background "red" :foreground "black"))))
     (jde-db-requested-breakpoint-face ((t (:background "yellow" :foreground "black"))))
     (jde-db-spec-breakpoint-face ((t (:background "green" :foreground "black"))))
     (jde-java-font-lock-api-face ((t (:foreground "light goldenrod"))))
     (jde-java-font-lock-bold-face ((t (:bold t :weight bold))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "light coral"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-link-face ((t (:foreground "cadetblue" :underline t))))
     (jde-java-font-lock-modifier-face ((t (:foreground "LightSteelBlue"))))
     (jde-java-font-lock-number-face ((t (:foreground "LightSalmon"))))
     (jde-java-font-lock-operator-face ((t (:foreground "medium blue"))))
     (jde-java-font-lock-package-face ((t (:foreground "steelblue1"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (lazy-highlight ((t (:background "darkseagreen" :foreground "black"))))
     (left-margin ((t (nil))))
     (link ((t (:foreground "cyan" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (list-mode-item-selected ((t (:background "gray68"))))
     (log-view-message-face ((t (:foreground "light salmon"))))
     (magenta ((t (:foreground "magenta"))))
     (makefile-space-face ((t (:background "hotpink"))))
     (match ((t (:background "blue" :foreground "white"))))
     (menu ((t (:bold t :background "black" :foreground "green" :box (:line-width -1 :color "#606060") :weight semi-bold))))
     (message-cited-text-face ((t (:italic t :background "black" :foreground "#00CC00" :slant oblique))))
     (message-header-cc-face ((t (nil))))
     (message-header-name-face ((t (nil))))
     (message-header-newsgroups-face ((t (:italic t :bold t :background "black" :foreground "#00CC00" :slant italic :weight bold))))
     (message-header-other-face ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (message-header-subject-face ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (message-header-to-face ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (message-header-xheader-face ((t (nil))))
     (message-mml-face ((t (:italic t :bold t :background "black" :foreground "#00CC00" :slant oblique :weight bold))))
     (message-separator-face ((t (nil))))
     (minibuffer-prompt ((t (:background "black" :foreground "seagreen"))))
     (mode-line ((t (:bold t :background "#404040" :foreground "green" :box (:line-width -1 :color "#606060") :weight semi-bold))))
     (mode-line-buffer-id ((t (:bold t :background "red" :foreground "yellow" :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:bold t :weight bold :foreground "#00CC00" :background "darkgreen"))))
     (mode-line-inactive ((t (:bold t :background "#101010" :foreground "green" :box (:line-width -1 :color "#606060") :weight semi-bold))))
     (modeline-mousable ((t (:background "red" :foreground "yellow"))))
     (modeline-mousable-minor-mode ((t (:background "red" :foreground "green4"))))
     (mouse ((t (:background "black"))))
     (next-error ((t (:foreground "black" :background "seagreen"))))
     (nobreak-space ((t (:background "magenta"))))
     (paren-blink-off ((t (:foreground "black"))))
     (paren-face ((t (:background "black" :foreground "darkgreen"))))
     (paren-face-match ((t (:background "black" :foreground "springgreen"))))
     (paren-face-mismatch ((t (:background "black" :foreground "#00CC00" :strike-through t))))
     (paren-face-no-match ((t (:background "black" :foreground "red"))))
     (paren-match ((t (:bold t :background "yellow" :foreground "red" :weight bold))))
     (paren-mismatch ((t (:background "DeepPink"))))
     (pointer ((t (nil))))
     (popup-face ((t (:background "lightgray" :foreground "black"))))
     (popup-isearch-match ((t (:background "sky blue"))))
     (popup-menu-face ((t (:background "lightgray" :foreground "black"))))
     (popup-menu-selection-face ((t (:background "steelblue" :foreground "white"))))
     (popup-scroll-bar-background-face ((t (:background "gray"))))
     (popup-scroll-bar-foreground-face ((t (:background "black"))))
     (popup-tip-face ((t (:background "khaki1" :foreground "black"))))
     (primary-selection ((t (:background "gray65"))))
     (pulse-highlight-face ((t (:background "#AAAA33"))))
     (pulse-highlight-start-face ((t (:background "#AAAA33"))))
     (query-replace ((t (:foreground "black" :background "seagreen"))))
     (red ((t (:foreground "red"))))
     (region ((t (:background "seagreen" :foreground "black"))))
     (right-margin ((t (nil))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "darkseagreen" :foreground "black"))))
     (semantic-decoration-on-includes ((t (nil))))
     (semantic-decoration-on-private-members-face ((t (:background "#200000"))))
     (semantic-decoration-on-protected-members-face ((t (:background "#000020"))))
     (semantic-decoration-on-unknown-includes ((t (:background "#900000"))))
     (semantic-decoration-on-unparsed-includes ((t (:background "#555500"))))
     (semantic-dirty-token-face ((t (:background "gray10"))))
     (semantic-highlight-edits-face ((t (:background "gray20"))))
     (semantic-highlight-func-current-tag-face ((t (:background "gray20"))))
     (semantic-tag-boundary-face ((t (:overline "cyan"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray75"))))
     (senator-momentary-highlight-face ((t (:background "gray30"))))
     (senator-read-only-face ((t (:background "#664444"))))
     (sgml-end-tag-face ((t (:foreground "seagreen"))))
     (sgml-start-tag-face ((t (:foreground "seagreen"))))
     (shadow ((t (:foreground "yellow"))))
     (show-paren-match-face ((t (:bold t :background "turquoise" :foreground "steel blue" :weight bold))))
     (show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
     (speedbar-button-face ((t (:foreground "green4"))))
     (speedbar-directory-face ((t (:foreground "blue4"))))
     (speedbar-file-face ((t (:foreground "cyan4"))))
     (speedbar-highlight-face ((t (:background "green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "brown"))))
     (tabbar-button-face ((t (:background "black" :foreground "#00cc00" :box (:line-width 2 :color "black" :style released-button)))))
     (tabbar-default-face ((t (:background "black" :foreground "#00cc00"))))
     (tabbar-selected-face ((t (:background "black" :foreground "springgreen" :box (:line-width 2 :color "black" :style released-button)))))
     (tabbar-separator-face ((t (:background "black" :foreground "#00cc00"))))
     (tabbar-unselected-face ((t (:background "black" :foreground "seagreen" :box (:line-width 2 :color "black" :style pressed-button)))))
     (template-message-face ((t (:bold t :weight bold))))
     (term-black ((t (:foreground "black"))))
     (term-blackbg ((t (nil))))
     (term-blue ((t (:foreground "blue"))))
     (term-blue-bold-face ((t (:bold t :foreground "blue" :weight bold))))
     (term-blue-face ((t (:foreground "blue"))))
     (term-blue-inv-face ((t (:background "blue"))))
     (term-blue-ul-face ((t (:foreground "blue" :underline t))))
     (term-bluebg ((t (:background "blue"))))
     (term-bold ((t (:bold t :weight bold))))
     (term-cyan ((t (:foreground "cyan"))))
     (term-cyan-bold-face ((t (:bold t :foreground "cyan" :weight bold))))
     (term-cyan-face ((t (:foreground "cyan"))))
     (term-cyan-inv-face ((t (:background "cyan"))))
     (term-cyan-ul-face ((t (:foreground "cyan" :underline t))))
     (term-cyanbg ((t (:background "cyan"))))
     (term-default-bg ((t (nil))))
     (term-default-bg-inv ((t (nil))))
     (term-default-bold-face ((t (:bold t :weight bold))))
     (term-default-face ((t (nil))))
     (term-default-fg ((t (nil))))
     (term-default-fg-inv ((t (nil))))
     (term-default-inv-face ((t (:background "peachpuff" :foreground "black"))))
     (term-default-ul-face ((t (:underline t))))
     (term-green ((t (:foreground "green"))))
     (term-green-bold-face ((t (:bold t :foreground "green" :weight bold))))
     (term-green-face ((t (:foreground "green"))))
     (term-green-inv-face ((t (:background "green"))))
     (term-green-ul-face ((t (:foreground "green" :underline t))))
     (term-greenbg ((t (:background "green"))))
     (term-invisible ((t (nil))))
     (term-invisible-inv ((t (nil))))
     (term-magenta ((t (:foreground "magenta"))))
     (term-magenta-bold-face ((t (:bold t :foreground "magenta" :weight bold))))
     (term-magenta-face ((t (:foreground "magenta"))))
     (term-magenta-inv-face ((t (:background "magenta"))))
     (term-magenta-ul-face ((t (:foreground "magenta" :underline t))))
     (term-magentabg ((t (:background "magenta"))))
     (term-red ((t (:foreground "red"))))
     (term-red-bold-face ((t (:bold t :foreground "red" :weight bold))))
     (term-red-face ((t (:foreground "red"))))
     (term-red-inv-face ((t (:background "red"))))
     (term-red-ul-face ((t (:foreground "red" :underline t))))
     (term-redbg ((t (:background "red"))))
     (term-underline ((t (:underline t))))
     (term-white ((t (:foreground "white"))))
     (term-white-bold-face ((t (:bold t :foreground "white" :weight bold))))
     (term-white-face ((t (:foreground "white"))))
     (term-white-inv-face ((t (nil))))
     (term-white-ul-face ((t (:foreground "white" :underline t))))
     (term-whitebg ((t (:background "white"))))
     (term-yellow ((t (:foreground "yellow"))))
     (term-yellow-bold-face ((t (:bold t :foreground "yellow" :weight bold))))
     (term-yellow-face ((t (:foreground "yellow"))))
     (term-yellow-inv-face ((t (:background "yellow"))))
     (term-yellow-ul-face ((t (:foreground "yellow" :underline t))))
     (term-yellowbg ((t (:background "yellow"))))
     (text-cursor ((t (:background "red" :foreground "black"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (nil))))
     (trailing-whitespace ((t (:background "lightseagreen" :foreground "black"))))
     (underline ((t (:background "black" :foreground "#00CC00" :underline t))))
     (variable-pitch ((t (:background "black" :foreground "#00CC00" :underline nil :family "Sans Serif"))))
     (vcursor ((t (:background "cyan" :foreground "blue" :underline t))))
     (vertical-border ((t (:bold t :weight semi-bold :box (:line-width -1 :color "#606060") :foreground "green" :background "#101010"))))
     (vertical-divider ((t (:background "Gray80" :foreground "black"))))
     (vhdl-font-lock-attribute-face ((t (:foreground "Orchid"))))
     (vhdl-font-lock-directive-face ((t (:foreground "CadetBlue"))))
     (vhdl-font-lock-enumvalue-face ((t (:foreground "Gold4"))))
     (vhdl-font-lock-function-face ((t (:foreground "Orchid4"))))
     (vhdl-font-lock-prompt-face ((t (:bold t :foreground "Red" :weight bold))))
     (vhdl-font-lock-reserved-words-face ((t (:bold t :foreground "Orange" :weight bold))))
     (vhdl-font-lock-translate-off-face ((t (:background "LightGray"))))
     (vhdl-speedbar-architecture-face ((t (:foreground "Blue"))))
     (vhdl-speedbar-architecture-selected-face ((t (:foreground "Blue" :underline t))))
     (vhdl-speedbar-configuration-face ((t (:foreground "DarkGoldenrod"))))
     (vhdl-speedbar-configuration-selected-face ((t (:foreground "DarkGoldenrod" :underline t))))
     (vhdl-speedbar-entity-face ((t (:foreground "ForestGreen"))))
     (vhdl-speedbar-entity-selected-face ((t (:foreground "ForestGreen" :underline t))))
     (vhdl-speedbar-instantiation-face ((t (:foreground "Brown"))))
     (vhdl-speedbar-instantiation-selected-face ((t (:foreground "Brown" :underline t))))
     (vhdl-speedbar-package-face ((t (:foreground "Grey50"))))
     (vhdl-speedbar-package-selected-face ((t (:foreground "Grey50" :underline t))))
     (viper-minibuffer-emacs-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-minibuffer-insert-face ((t (:background "pink" :foreground "Black"))))
     (viper-minibuffer-vi-face ((t (:background "grey" :foreground "DarkGreen"))))
     (viper-replace-overlay-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-search-face ((t (:background "khaki" :foreground "Black"))))
     (w3m-anchor-face ((t (:bold t :foreground "DodgerBlue1" :weight bold))))
     (w3m-arrived-anchor-face ((t (:bold t :foreground "DodgerBlue3" :weight bold))))
     (w3m-header-line-location-content-face ((t (:background "dark olive green" :foreground "wheat"))))
     (w3m-header-line-location-title-face ((t (:background "dark olive green" :foreground "beige"))))
     (which-func ((t (:foreground "Blue1"))))
     (white ((t (:foreground "white"))))
     (widget ((t (:background "Gray80" :foreground "black"))))
     (widget-button ((t (:bold t :background "black" :foreground "#00CC00" :weight bold))))
     (widget-button-pressed ((t (nil))))
     (widget-documentation ((t (nil))))
     (widget-field ((t (:italic t :background "black" :foreground "#00CC00" :slant oblique))))
     (widget-inactive ((t (nil))))
     (widget-single-line-field ((t (nil))))
     (woman-bold-face ((t (:bold t :weight bold))))
     (woman-italic-face ((t (:foreground "beige"))))
     (woman-unknown-face ((t (:foreground "LightSalmon"))))
     (x-face ((t (:bold t :background "wheat" :foreground "black" :weight bold))))
     (xrdb-option-name-face ((t (:bold t :foreground "yellow" :weight bold))))
     (xrdb-option-value-face ((t (:bold t :foreground "magenta" :weight bold))))
     (yellow ((t (:foreground "yellow"))))
     (zmacs-region ((t (:background "white" :foreground "black")))))))
(add-to-list 'color-themes '(my-color-theme  "THEME NAME" "YOUR NAME"))